### ISSUE TITLE
Duplicate repository?

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn_old#14]
`e3nn` is not listed in Github searches because it is a fork of the `se3nn` repo. This also causes complications with pull requests. We should probably simplify things by breaking the fork and "starting fresh"

Information on duplicating repositories on [Github](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository)

**Comment by bkmi** [comment]
agreed, also maintaining both is going to get crazy.

**Comment by mariogeiger** [comment]
Done
